### ISSUE TITLE
Why 0.0.0 is treated as an invalid version?

### ISSUE THREAD

**Issue by z4kn4fein** [skuzzle/semantic-version#4]
Is there a specific reason why the 0.0.0 is treated as an illegal version? I'm just courious, because it counts as a valid semantic version. Is there a chance to make this check optional?

**Comment by skuzzle** [comment]
Hm, I guess i made up that rule because it made sense to be. But you are completely right about `0.0.0` being a valid semantic version and as such should be accepted by the API.
I will change this but I'll have to resolve #3 too before I'll be able to release a new version. Stay tuned.

**Comment by z4kn4fein** [comment]
Thanks for the quick reply and solution!

**Comment by skuzzle** [comment]
Released as 2.1.0
